// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rtty.proto

/*
Package rtty is a generated protocol buffer package.

It is generated from these files:
	rtty.proto

It has these top-level messages:
	RttyMessage
*/
package rtty

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RttyMessage_Type int32

const (
	RttyMessage_UNKNOWN  RttyMessage_Type = 0
	RttyMessage_LOGIN    RttyMessage_Type = 1
	RttyMessage_LOGINACK RttyMessage_Type = 2
	RttyMessage_LOGOUT   RttyMessage_Type = 3
	RttyMessage_TTY      RttyMessage_Type = 4
	RttyMessage_COMMAND  RttyMessage_Type = 5
	RttyMessage_WINSIZE  RttyMessage_Type = 6
)

var RttyMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOGIN",
	2: "LOGINACK",
	3: "LOGOUT",
	4: "TTY",
	5: "COMMAND",
	6: "WINSIZE",
}
var RttyMessage_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"LOGIN":    1,
	"LOGINACK": 2,
	"LOGOUT":   3,
	"TTY":      4,
	"COMMAND":  5,
	"WINSIZE":  6,
}

func (x RttyMessage_Type) String() string {
	return proto.EnumName(RttyMessage_Type_name, int32(x))
}
func (RttyMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type RttyMessage_LoginCode int32

const (
	RttyMessage_OK      RttyMessage_LoginCode = 0
	RttyMessage_OFFLINE RttyMessage_LoginCode = 1
)

var RttyMessage_LoginCode_name = map[int32]string{
	0: "OK",
	1: "OFFLINE",
}
var RttyMessage_LoginCode_value = map[string]int32{
	"OK":      0,
	"OFFLINE": 1,
}

func (x RttyMessage_LoginCode) String() string {
	return proto.EnumName(RttyMessage_LoginCode_name, int32(x))
}
func (RttyMessage_LoginCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type RttyMessage_CommandErr int32

const (
	RttyMessage_NONE           RttyMessage_CommandErr = 0
	RttyMessage_TIMEOUT        RttyMessage_CommandErr = 1
	RttyMessage_NOTFOUND       RttyMessage_CommandErr = 2
	RttyMessage_READ           RttyMessage_CommandErr = 3
	RttyMessage_PERMISSION     RttyMessage_CommandErr = 4
	RttyMessage_SYSCALL        RttyMessage_CommandErr = 5
	RttyMessage_DEV_OFFLINE    RttyMessage_CommandErr = 6
	RttyMessage_CMD_REQUIRED   RttyMessage_CommandErr = 7
	RttyMessage_DEVID_REQUIRED RttyMessage_CommandErr = 8
)

var RttyMessage_CommandErr_name = map[int32]string{
	0: "NONE",
	1: "TIMEOUT",
	2: "NOTFOUND",
	3: "READ",
	4: "PERMISSION",
	5: "SYSCALL",
	6: "DEV_OFFLINE",
	7: "CMD_REQUIRED",
	8: "DEVID_REQUIRED",
}
var RttyMessage_CommandErr_value = map[string]int32{
	"NONE":           0,
	"TIMEOUT":        1,
	"NOTFOUND":       2,
	"READ":           3,
	"PERMISSION":     4,
	"SYSCALL":        5,
	"DEV_OFFLINE":    6,
	"CMD_REQUIRED":   7,
	"DEVID_REQUIRED": 8,
}

func (x RttyMessage_CommandErr) String() string {
	return proto.EnumName(RttyMessage_CommandErr_name, int32(x))
}
func (RttyMessage_CommandErr) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

type RttyMessage struct {
	Version  uint32            `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Type     RttyMessage_Type  `protobuf:"varint,2,opt,name=type,enum=RttyMessage_Type" json:"type,omitempty"`
	Sid      string            `protobuf:"bytes,3,opt,name=sid" json:"sid,omitempty"`
	Code     int32             `protobuf:"varint,4,opt,name=code" json:"code,omitempty"`
	Data     []byte            `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Name     string            `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Size     uint32            `protobuf:"varint,7,opt,name=size" json:"size,omitempty"`
	Id       uint32            `protobuf:"varint,8,opt,name=id" json:"id,omitempty"`
	Err      int32             `protobuf:"varint,9,opt,name=err" json:"err,omitempty"`
	Username string            `protobuf:"bytes,10,opt,name=username" json:"username,omitempty"`
	Password string            `protobuf:"bytes,11,opt,name=password" json:"password,omitempty"`
	StdOut   string            `protobuf:"bytes,12,opt,name=std_out,json=stdOut" json:"std_out,omitempty"`
	StdErr   string            `protobuf:"bytes,13,opt,name=std_err,json=stdErr" json:"std_err,omitempty"`
	Params   []string          `protobuf:"bytes,14,rep,name=params" json:"params,omitempty"`
	Env      map[string]string `protobuf:"bytes,15,rep,name=env" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cols     uint32            `protobuf:"varint,16,opt,name=cols" json:"cols,omitempty"`
	Rows     uint32            `protobuf:"varint,17,opt,name=rows" json:"rows,omitempty"`
}

func (m *RttyMessage) Reset()                    { *m = RttyMessage{} }
func (m *RttyMessage) String() string            { return proto.CompactTextString(m) }
func (*RttyMessage) ProtoMessage()               {}
func (*RttyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RttyMessage) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RttyMessage) GetType() RttyMessage_Type {
	if m != nil {
		return m.Type
	}
	return RttyMessage_UNKNOWN
}

func (m *RttyMessage) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *RttyMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RttyMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RttyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RttyMessage) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RttyMessage) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RttyMessage) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *RttyMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RttyMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RttyMessage) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

func (m *RttyMessage) GetStdErr() string {
	if m != nil {
		return m.StdErr
	}
	return ""
}

func (m *RttyMessage) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RttyMessage) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *RttyMessage) GetCols() uint32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func (m *RttyMessage) GetRows() uint32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func init() {
	proto.RegisterType((*RttyMessage)(nil), "rtty_message")
	proto.RegisterEnum("RttyMessage_Type", RttyMessage_Type_name, RttyMessage_Type_value)
	proto.RegisterEnum("RttyMessage_LoginCode", RttyMessage_LoginCode_name, RttyMessage_LoginCode_value)
	proto.RegisterEnum("RttyMessage_CommandErr", RttyMessage_CommandErr_name, RttyMessage_CommandErr_value)
}

func init() { proto.RegisterFile("rtty.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x52, 0x4f, 0x6b, 0xdb, 0x30,
	0x14, 0xaf, 0xed, 0xd8, 0x89, 0x5f, 0xd2, 0x54, 0x13, 0xa3, 0x13, 0x3d, 0x99, 0x1c, 0x86, 0x4f,
	0x3d, 0x74, 0x30, 0xc6, 0x6e, 0xc1, 0x56, 0x8b, 0xa9, 0x23, 0x6d, 0x8a, 0xd3, 0xd2, 0xed, 0x10,
	0xbc, 0x59, 0x14, 0xb3, 0xc6, 0x0e, 0x92, 0x93, 0x92, 0x7d, 0x89, 0x7d, 0xd6, 0x7d, 0x83, 0x21,
	0x99, 0x94, 0xee, 0xf6, 0xfb, 0xf3, 0xfe, 0xe9, 0x3d, 0x01, 0xa8, 0xae, 0x3b, 0x5c, 0x6e, 0x55,
	0xdb, 0xb5, 0xb3, 0xbf, 0x3e, 0x4c, 0x0c, 0x5d, 0x6f, 0xa4, 0xd6, 0xe5, 0xa3, 0xc4, 0x04, 0x86,
	0x7b, 0xa9, 0x74, 0xdd, 0x36, 0xc4, 0x89, 0x9c, 0xf8, 0x54, 0x1c, 0x29, 0x7e, 0x0f, 0x83, 0xee,
	0xb0, 0x95, 0xc4, 0x8d, 0x9c, 0x78, 0x7a, 0x85, 0x2f, 0x5f, 0xa7, 0x5d, 0x16, 0x87, 0xad, 0x14,
	0xd6, 0xc7, 0x08, 0x3c, 0x5d, 0x57, 0xc4, 0x8b, 0x9c, 0x38, 0x14, 0x06, 0x62, 0x0c, 0x83, 0x9f,
	0x6d, 0x25, 0xc9, 0x20, 0x72, 0x62, 0x5f, 0x58, 0x6c, 0xb4, 0xaa, 0xec, 0x4a, 0xe2, 0x47, 0x4e,
	0x3c, 0x11, 0x16, 0x1b, 0xad, 0x29, 0x37, 0x92, 0x04, 0x36, 0xd5, 0x62, 0xa3, 0xe9, 0xfa, 0xb7,
	0x24, 0x43, 0x3b, 0x8c, 0xc5, 0x78, 0x0a, 0x6e, 0x5d, 0x91, 0x91, 0x55, 0xdc, 0xba, 0x32, 0x1d,
	0xa5, 0x52, 0x24, 0xb4, 0xe5, 0x0d, 0xc4, 0x17, 0x30, 0xda, 0x69, 0xa9, 0x6c, 0x35, 0xb0, 0xd5,
	0x5e, 0xb8, 0xf1, 0xb6, 0xa5, 0xd6, 0xcf, 0xad, 0xaa, 0xc8, 0xb8, 0xf7, 0x8e, 0x1c, 0xbf, 0x83,
	0xa1, 0xee, 0xaa, 0x75, 0xbb, 0xeb, 0xc8, 0xc4, 0x5a, 0x81, 0xee, 0x2a, 0xbe, 0xeb, 0x8e, 0x86,
	0x69, 0x73, 0xfa, 0x62, 0x50, 0xa5, 0xf0, 0x39, 0x04, 0xdb, 0x52, 0x95, 0x1b, 0x4d, 0xa6, 0x91,
	0x67, 0xf4, 0x9e, 0xe1, 0x18, 0x3c, 0xd9, 0xec, 0xc9, 0x59, 0xe4, 0xc5, 0xe3, 0xab, 0xf3, 0xff,
	0x97, 0x45, 0x9b, 0x3d, 0x6d, 0x3a, 0x75, 0x10, 0x26, 0xa4, 0xdf, 0xce, 0x93, 0x26, 0xa8, 0x7f,
	0xa1, 0xc1, 0x46, 0x53, 0xed, 0xb3, 0x26, 0x6f, 0x7a, 0xcd, 0xe0, 0x8b, 0x8f, 0x30, 0x3a, 0x26,
	0x9a, 0x17, 0xff, 0x92, 0x07, 0x7b, 0xa1, 0x50, 0x18, 0x88, 0xdf, 0x82, 0xbf, 0x2f, 0x9f, 0x76,
	0xfd, 0x79, 0x42, 0xd1, 0x93, 0xcf, 0xee, 0x27, 0x67, 0xf6, 0x1d, 0x06, 0xe6, 0x3a, 0x78, 0x0c,
	0xc3, 0x15, 0xbb, 0x65, 0xfc, 0x9e, 0xa1, 0x13, 0x1c, 0x82, 0x9f, 0xf3, 0x9b, 0x8c, 0x21, 0x07,
	0x4f, 0x60, 0x64, 0xe1, 0x3c, 0xb9, 0x45, 0x2e, 0x06, 0x08, 0x72, 0x7e, 0xc3, 0x57, 0x05, 0xf2,
	0xf0, 0x10, 0xbc, 0xa2, 0x78, 0x40, 0x03, 0x93, 0x9a, 0xf0, 0xc5, 0x62, 0xce, 0x52, 0xe4, 0x1b,
	0x72, 0x9f, 0xb1, 0x65, 0xf6, 0x8d, 0xa2, 0x60, 0x16, 0x41, 0x98, 0xb7, 0x8f, 0x75, 0x93, 0x98,
	0x9b, 0x06, 0xe0, 0xf2, 0x5b, 0x74, 0x62, 0x22, 0xf8, 0xf5, 0x75, 0x9e, 0x31, 0x8a, 0x9c, 0xd9,
	0x1f, 0x07, 0x20, 0x69, 0x37, 0x9b, 0xb2, 0xb1, 0xfb, 0x1a, 0xc1, 0x80, 0x71, 0x46, 0xfb, 0xa8,
	0x22, 0x5b, 0x50, 0xd3, 0xca, 0x0e, 0xc1, 0x78, 0x71, 0xcd, 0x57, 0x2c, 0x45, 0xae, 0x09, 0x12,
	0x74, 0x9e, 0x22, 0x0f, 0x4f, 0x01, 0xbe, 0x50, 0xb1, 0xc8, 0x96, 0xcb, 0x8c, 0xb3, 0x7e, 0x92,
	0xe5, 0xc3, 0x32, 0x99, 0xe7, 0x39, 0xf2, 0xf1, 0x19, 0x8c, 0x53, 0x7a, 0xb7, 0x3e, 0xf6, 0x0a,
	0x30, 0x82, 0x49, 0xb2, 0x48, 0xd7, 0x82, 0x7e, 0x5d, 0x65, 0x82, 0xa6, 0x68, 0x88, 0x31, 0x4c,
	0x53, 0x7a, 0x97, 0xbd, 0xd2, 0x46, 0x3f, 0x02, 0xfb, 0xf5, 0x3f, 0xfc, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x4b, 0xb6, 0xc9, 0x16, 0x08, 0x03, 0x00, 0x00,
}
